services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: daniel
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres_network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_:PASSWORD: ${PGADMIN_DEFAULT_PASSWORD-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_network
    depends_on:
      - postgres
    restart: unless-stopped

  zipkin:
   image: openzipkin/zipkin
   container_name: zipkin
   ports:
     - "9411:9411"
   networks:
     - postgres_network

networks:
  postgres_network:
    driver: bridge
    name: postgres_network

volumes:
  postgres:
  pgadmin:
