spring:
  application:
    name: company-service
#  datasource:
#    url: jdbc:h2:mem:test
#  h2:
#    console:
#      enabled: true
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/company
    username: daniel
    password: daniel
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8081

# Eureka
eureka:
  client:
    registry-withf-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

#Zipkin
management:
  trading:
    sampling:
      probability: 1.0
